### ISSUE TITLE
What's the default protocol if none is specified?

### ISSUE THREAD

**Issue by heinrich5991** [Debian/wcurl#1]
In the README, I see examples like:

> Download a single file:
> wcurl example.com/filename.txt

I'm wondering whether this uses https://example.com/filename.txt if no scheme is given. Perhaps the example could indicate that?

**Comment by samueloph** [comment]
All URL parsing is done by curl, which for this case follows the rules described at https://curl.se/docs/url-syntax.html#scheme-less

So for the example, HTTP is used.

I'll keep this open since we could explain that better in the README/manpage.

**Comment by heinrich5991** [comment]
Perhaps you could pass `--proto-default https` so that downloads are secured by HTTPS by default (instead of relying on insecure HTTP→HTTPS redirects).
