### ISSUE TITLE
[idea] Content-Disposition Header for file name

### ISSUE THREAD

**Issue by Bloodiko** [Debian/wcurl#2]
As I did not see it in the script, 
Would it be possible for wcurl to possibly read the Content-Disposition Header to autogenerate the filename ? 

Some endpoints especially API endpoints may end on "/download" but respond with a Content-Disposition Header like 

```
attachment; filename="File-From-Download.txt"; filename*=UTF8''File-From-Download.txt
```

**Comment by heinrich5991** [comment]
That sounds like a security issue, giving the server the ability to overwrite an arbitrary file in the current directory. It should probably not be on by default.

**Comment by samueloph** [comment]
@Bloodiko That's item number 3 from this email thread:
https://curl.se/mail/lib-2024-06/0030.html

It's not possible to use both `--remote-name` and `--continue-at`.
It requires changes to the curl CLI.

**Comment by Bloodiko** [comment]
> That sounds like a security issue, giving the server the ability to overwrite an arbitrary file in the current directory. It should probably not be on by default.

Ohh, right. That's actually a good point I forgot. 
Thanks for that.

Will continue to do it manually.

Will close this, thanks for the answers.
