### ISSUE TITLE
Requires util-linux version of getopt

### ISSUE THREAD

**Issue by ryandesign** [Debian/wcurl#3]
As [pointed out by tssva](https://news.ycombinator.com/item?id=40873627) on Hacker News, wcurl 2024-07-02 requires the util-linux version of getopt. If using the version of getopt that comes with macOS, it does this:

```
% wcurl --help             
curl: option --longoptions: is unknown
curl: try 'curl --help' or 'curl --manual' for more information
```

**Comment by ryandesign** [comment]
(I've filed the issue here, even though this is a mirror of the GitLab repo, because there is no issue tracker enabled on the GitLab repo; please enable it there if you want to keep issues and MRs together in one place.)

**Comment by samueloph** [comment]
> (I've filed the issue here, even though this is a mirror of the GitLab repo, because there is no issue tracker enabled on the GitLab repo; please enable it there if you want to keep issues and MRs together in one place.)

Either one is fine by me.

sergiodj has worked on fixing this and also adding a few other improvements (he's likely going to update the MR still): https://salsa.debian.org/debian/wcurl/-/merge_requests/5

I plan on merging this (and dealing with other issues) tomorrow.

Thank you for reviewing and raising all the issues you did!
