### ISSUE TITLE
Create tags for released versions

### ISSUE THREAD

**Issue by ryandesign** [Debian/wcurl#6]
While I know wcurl is included in the debian curl package, it was announced to the curl-distros list and other distributions were invited to package it as well. To do that, other package systems would prefer to download an official version from a tag rather than from some random commit.

Please create tags for all of the released versions:

* 2024-05-14 = 110ec46248c855c75cb357d1ecc15d6d7b6c3d4c
* 2024-06-26 = 2deb288fbbd4c46d539114bb2a1ccdd90ab1c699
* 2024-07-02 = e4a7f678f4b9ba473fc51b51c2f0e02c74134d3c

**Comment by samueloph** [comment]
Will do within the next couple of days, thank you!

**Comment by samueloph** [comment]
Tags pushed, from now on I'll tag all future releases with my GPG key: `BFAE9E331A867A7C80D8EB78F4E4ACDBB8D08BE0`.

Thank you for the suggestion.
