### ISSUE TITLE
wcurl tries to continue downloading an existing file

### ISSUE THREAD

**Issue by ryandesign** [Debian/wcurl#8]
When wget 1.24.5 encounters an existing file it appends a dot and a number:

```
% touch index.html
% ls -l index.html*  
-rw-r--r--  1 rschmidt  wheel  0 Jul  4 12:52 index.html
% wget github.com/index.html
URL transformed to HTTPS due to an HSTS policy
--2024-07-04 12:52:46--  https://github.com/index.html
Resolving github.com (github.com)... 140.82.114.3
Connecting to github.com (github.com)|140.82.114.3|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘index.html.1’

index.html.1                                                           [ <=>                                                                                                                                                           ] 126.43K   771KB/s    in 0.2s    

2024-07-04 12:52:47 (771 KB/s) - ‘index.html.1’ saved [129465]

% ls -l index.html*         
-rw-r--r--  1 rschmidt  wheel       0 Jul  4 12:52 index.html
-rw-r--r--  1 rschmidt  wheel  129465 Jul  4 12:52 index.html.1
% rm index.html*            
```

wcurl 2024-07-02 just overwrites the existing file which may be unexpected:

```
% touch index.html
% ls -l index.html*
-rw-r--r--  1 rschmidt  wheel  0 Jul  4 12:51 index.html
% wcurl github.com/index.html
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  126k    0  126k    0     0   222k      0 --:--:-- --:--:-- --:--:--  334k
% ls -l index.html*          
-rw-r--r--  1 rschmidt  wheel  129466 Jul  4 12:51 index.html
% rm index.html*
```

Fix this by adding `--no-clobber` to the curl flags that get added by default:

```
% touch index.html          
% ls -l index.html*
-rw-r--r--  1 rschmidt  wheel  0 Jul  4 12:54 index.html
% wcurl --opts=--no-clobber github.com/index.html 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  126k    0  126k    0     0   214k      0 --:--:-- --:--:-- --:--:--  798k
% ls -l index.html*                              
-rw-r--r--  1 rschmidt  wheel       0 Jul  4 12:54 index.html
-rw-r--r--  1 rschmidt  wheel  129478 Jul  4 12:54 index.html.1
```

**Comment by ryandesign** [comment]
My test wasn't completely accurate due to using empty existing files. If I use a non-empty existing file, behavior is different:

```
% echo hi > index.html
% ls -l index.html*                                   
-rw-r--r--  1 rschmidt  wheel  3 Jul  4 13:10 index.html
% wcurl github.com/index.html                       
** Resuming transfer from byte position 3
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (33) HTTP server doesn't seem to support byte ranges. Cannot resume.
```

The problem is a difference in continuation behavior.

wget will by default not clobber or continue downloading from a file that existed before wget was started. But if the connection is dropped and wget has to retry, then it will try to continue where it left off. If you want wget to continue from a file that existed before wget was started, use the `-c` flag.

I can't test it right now because I don't know of an unreliable server that would drop the connection in the middle of a download, but according to the manpage curl on the other hand does not distinguish between continuing on the first attempt vs continuing on retries. It either does not try to continue (the default) or it does try to continue (if you use the `-C -` flag).

**Comment by samueloph** [comment]
I believe the `--no-clobber` option address this, we just need to do some tests.

**Comment by samueloph** [comment]
Right, so we have to decide which feature to keep, either we resume interrupter transfers by default (`--continue-at`), or we avoid overwriting files (`--no-clobber`).

We can/should submit a feature request to curl to support both, but that's probably not going to be trivial work, for now we need to decide which one to choose.

Feel free to let us know your thoughts on this.

It seems like `--no-clobber` is the safest approach.

**Comment by samueloph** [comment]
Fixed at https://github.com/Debian/wcurl/commit/1484f08ef32e8222b333851661c4841a3c831f3a

From the changelog:
* Stop auto-resuming downloads and don't overwrite files instead by default.
   Safer alternative as otherwise curl can corrupt a file if the name clashes and the size of the existing one is smaller.
   One can easily change that behavior with '--curl-options="--continue-at -".'

Thank you
